# Generated by Django 2.2.4 on 2020-05-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='emp_id',
        ),
    ]
